### ISSUE TITLE
Uploading Level.sav and exporting it causes problems

### ISSUE THREAD

**Issue by Jernee** [iebb/PalworldSaveEditor#1]
I uploaded my level.sav from my dedicated server to try and edit some settings after a friend got sorta shadow banned from a guild glitch. When I exported it to the server it makes me make a new character and eventually overwrites the level.sav with a fresh one. I suspected it was my fault after editing the .sav file but I uploaded a backup that I know works and exported it without making any changes and still get the same issue.

**Comment by iebb** [comment]
have messed up the magic bytes a bit, thanks for pointing out this; should have been fixed now
