### ISSUE TITLE
Website only exports old file

### ISSUE THREAD

**Issue by Kefkism** [iebb/PalworldSaveEditor#2]
Recent update seems to have broken something. The website only exports the original uploaded sav and not the modified sav file

**Comment by RemYeet** [comment]
same issue here, spent hours trying to figure out why we couldn't properly swap our characters when trying to exchange worlds with my buddy.

**Comment by iebb** [comment]
should be fixed now (a typo in `setContent` function name), sorry for the disruption caused :(
